## Creating one dimensional array

In [15]:
import numpy as np
a=[1,2,3,4,5]
myarray=np.array(a)
print(myarray)
print(type(myarray))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [7]:
a=[]
n=int(input('Enter size of array'))
for i in range(n):
    val=int(input('enter number'))
    a.append(val)
arr1=np.array(a)    
arr1



array([ 12, 123,  25,  35, 456])

## Creating two dimensional array

In [17]:
import numpy as np                         #a=[[1,2,3],[4,5,6],[7,8,9]]
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])      #arr2=np.array(a)
arr2                                          #arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
# Printing dimension and shape of array
print('Total dimensions-',arr2.ndim)
print('Shape of array-',arr2.shape)

Total dimensions- 2
Shape of array- (3, 3)


In [1]:
import numpy as  np

In [2]:
# creating array with arange function of numpy
a= np.arange(15) #single dimensional
print(a)
a= np.arange(15).reshape(3,5) #multidimentional array
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


## Numpy array properties

In [3]:
# size of array
a.size

15

In [4]:
# dimensions of array
a.ndim

2

In [6]:
x=np.array([1,3,4,5,6])
print(x)

[1 3 4 5 6]


In [7]:
y= np.array([[1,2,3],[2,3,4]])
print(y)

[[1 2 3]
 [2 3 4]]


In [9]:
print('shape',x.shape)
print('num of dimension:',x.ndim)
print('type of data:',x.dtype)
print('Y')
print('shape:',y.shape)
print('num of dimensions:',y.ndim)
print('type of data:',y.dtype)

shape (5,)
num of dimension: 1
type of data: int32
Y
shape: (2, 3)
num of dimensions: 2
type of data: int32


## Functions of array
- arange
- linspace
- random.*
- eye
- ones
- zeros
- diag
- rand


## arange()

In [52]:
print(np.arange(1,10))
print(np.arange(3.0))
print(np.arange(1,10,2))
print(np.arange(20,dtype=complex))
print(np.arange(1,10,2,dtype=float))    #(start,end,difference)

[1 2 3 4 5 6 7 8 9]
[0. 1. 2.]
[1 3 5 7 9]
[ 0.+0.j  1.+0.j  2.+0.j  3.+0.j  4.+0.j  5.+0.j  6.+0.j  7.+0.j  8.+0.j
  9.+0.j 10.+0.j 11.+0.j 12.+0.j 13.+0.j 14.+0.j 15.+0.j 16.+0.j 17.+0.j
 18.+0.j 19.+0.j]
[1. 3. 5. 7. 9.]


In [53]:
a= np.arange(-10,10,1.25) #last value excluded
print(a)

[-10.    -8.75  -7.5   -6.25  -5.    -3.75  -2.5   -1.25   0.     1.25
   2.5    3.75   5.     6.25   7.5    8.75]


In [13]:
b= np.linspace(0,1,10) #last value included
print(b)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [17]:
np.random.random((3,3)) #random values b/w zero to one

array([[0.54316737, 0.53228784, 0.7722473 ],
       [0.75536363, 0.48996587, 0.61281138],
       [0.11486366, 0.80346745, 0.437965  ]])

## randint()- this function is used to generate a random number between a given range.
- syntax is 
- rand(min,max,total_values)
- eg. arr=np.random.randint(1,10,3)
- output may be any 3 no. from 1 to 9


In [55]:
arr_4=np.random.randint(1,10,4)
arr_4

array([5, 1, 6, 9])

In [16]:
np.random.randint(1,1000,(3,3)) # random values b/w start and end/last value not included

array([[957, 863, 947],
       [675, 857, 354],
       [115, 644, 114]])

## rand()
- this function is used to generate a random values between 0 to 1.
- syntax- rand(number_of_values)


In [42]:
arr_5=np.random.rand(5)
arr_5

array([0.34403373, 0.39470234, 0.14427144, 0.59292387, 0.51688099])

In [43]:
arr_5=np.random.rand(2,3)
arr_5

array([[0.39394179, 0.42043355, 0.20530146],
       [0.75786225, 0.30247165, 0.11704319]])

## randn()- this function is used to generate a random vlaues close to 0.This may return positive or negative numbers as well.
- syntax
- rand.(number_of_values)
- output may be any 5 numbers from centered to 0

In [46]:
arr_6=np.random.randn(5)
arr_6

array([-0.16686118,  1.10752726, -0.42335216,  2.00739285,  0.56976806])

In [47]:
arr_6=np.random.randn(3,3)
arr_6

array([[ 1.39963481,  0.31272754,  1.54394253],
       [-1.12592068, -0.79988494,  1.22494796],
       [ 0.33900149, -1.01285855, -1.10066863]])

## eye()
- This function creates an array with all the diagonal elements as 1 and rest as 0 (in a square matrix). In case of a non-square matrix the values are still 1 for diagonal (upto which it can draw diagonal) and rest are zero

In [31]:
arr_1=np.eye(3)
arr_1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
arr_1=np.eye(3,5)
arr_1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [35]:
np.eye(5,dtype=int) #identity matrix

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

## Ones()

In [20]:
arr4=np.ones(4)
arr4

array([1., 1., 1., 1.])

In [30]:
import numpy as np
arr5=np.ones((2,4))
arr5

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
np.ones((5,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Zeros()

In [18]:
import numpy as np
arr3=np.zeros(5)
arr3

array([0., 0., 0., 0., 0.])

In [19]:
import numpy as np
arr3=np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.zeros((5,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

## diag()
- This function creates a two dimensional array with all the diagonal elements as the given value and rest as 0 (in a square matrix)

In [37]:
arr_2=np.diag([1,2,3,5,6])
arr_2

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 5, 0],
       [0, 0, 0, 0, 6]])

## To get the diagonal elements in a two dimensional array we use diag as a function

In [39]:
arr_3=np.diag([1,2,3,4])
print(arr_3)
np.diag(arr_3)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


array([1, 2, 3, 4])

# operations
- arithmetic
- statistical
- trignometric
- logical
- slicing
- filtering
- sorting

In [22]:
x= np.random.randint(1,25,(2,3))
y= np.random.randint(1,25,(3,2))
print(x)
print(y)

[[14  3  9]
 [10 19 13]]
[[ 4  6]
 [ 9 23]
 [ 1 24]]


In [23]:
y.T

array([[ 4,  9,  1],
       [ 6, 23, 24]])

In [24]:
print('x+y transposed')
print(x + y.T)
print('x transposed + y')
print(x.T+y)

x+y transposed
[[18 12 10]
 [16 42 37]]
x transposed + y
[[18 16]
 [12 42]
 [10 37]]


In [25]:
print('x+y transposed')
print(x - y.T)
print('x transposed + y')
print(x.T-y)

x+y transposed
[[ 10  -6   8]
 [  4  -4 -11]]
x transposed + y
[[ 10   4]
 [ -6  -4]
 [  8 -11]]


In [26]:
print('matix multiplication elemetwise')
print(x * y.T)
print('matix multiplicaton')
print(x @ y)


matix multiplication elemetwise
[[ 56  27   9]
 [ 60 437 312]]
matix multiplicaton
[[ 92 369]
 [224 809]]


In [27]:
np.hstack((x,x,x,x,x))

array([[14,  3,  9, 14,  3,  9, 14,  3,  9, 14,  3,  9, 14,  3,  9],
       [10, 19, 13, 10, 19, 13, 10, 19, 13, 10, 19, 13, 10, 19, 13]])

In [28]:
np.hstack((x,x,y.T))

array([[14,  3,  9, 14,  3,  9,  4,  9,  1],
       [10, 19, 13, 10, 19, 13,  6, 23, 24]])

In [30]:
print(x)
print('sum of all elements:',x.sum())
print('sum of all elements row wise:',x.sum(axis=1))
print('sum of all elements col  wise:',x.sum(axis=0))
print('average of all elements :',x.mean(axis=0))
print('median of all elements :',np.median(x))
print('min of all elements :',x.min())
print('max of all elements :',x.max())
print('std of all elements :',x.std())
print('variance of all elements :',x.var())
print('any item is non-zero',x.any())
print('all item are non-zero',x.all())


[[14  3  9]
 [10 19 13]]
sum of all elements: 68
sum of all elements row wise: [26 42]
sum of all elements col  wise: [24 22 22]
average of all elements : [12. 11. 11.]
median of all elements : 11.5
min of all elements : 3
max of all elements : 19
std of all elements : 4.921607686744467
variance of all elements : 24.222222222222225
any item is non-zero True
all item are non-zero True


In [31]:
print(np.pi)
print(np.nan)
print(np.inf)
print(np.e)

3.141592653589793
nan
inf
2.718281828459045


In [32]:
print(np.sin(x))
print(np.cos(x))
print(np.tan(x))

[[ 0.99060736  0.14112001  0.41211849]
 [-0.54402111  0.14987721  0.42016704]]
[[ 0.13673722 -0.9899925  -0.91113026]
 [-0.83907153  0.98870462  0.90744678]]
[[ 7.24460662 -0.14254654 -0.45231566]
 [ 0.64836083  0.15158947  0.46302113]]
