## Creating one dimensional array

In [9]:
import numpy as np
a=[1,2,3,4,5]
myarray=np.array(a)
print(myarray)
print(type(myarray))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [10]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [11]:
a=[]
n=int(input('Enter size of array'))
for i in range(n):
    val=int(input('enter number'))
    a.append(val)
arr1=np.array(a)    
arr1



array([1, 2, 3, 4, 5])

## Creating two dimensional array

In [12]:
import numpy as np                         #a=[[1,2,3],[4,5,6],[7,8,9]]
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])      #arr2=np.array(a)
arr2                                          #arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
# Printing dimension and shape of array
print('Total dimensions-',arr2.ndim)
print('Shape of array-',arr2.shape)

Total dimensions- 2
Shape of array- (3, 3)


In [14]:
import numpy as  np

In [15]:
# creating array with arange function of numpy
a= np.arange(15) #single dimensional
print(a)
a= np.arange(15).reshape(3,5) #multidimentional array
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


## Numpy array properties

In [16]:
# size of array
a.size

15

In [17]:
# dimensions of array
a.ndim

2

In [18]:
x=np.array([1,3,4,5,6])
print(x)

[1 3 4 5 6]


In [19]:
y= np.array([[1,2,3],[2,3,4]])
print(y)

[[1 2 3]
 [2 3 4]]


In [20]:
print('shape',x.shape)
print('num of dimension:',x.ndim)
print('type of data:',x.dtype)
print('Y')
print('shape:',y.shape)
print('num of dimensions:',y.ndim)
print('type of data:',y.dtype)

shape (5,)
num of dimension: 1
type of data: int32
Y
shape: (2, 3)
num of dimensions: 2
type of data: int32


## Functions of array
- arange
- linspace
- random.*
- eye
- ones
- zeros
- diag
- rand


## arange()

In [21]:
print(np.arange(1,10))
print(np.arange(3.0))
print(np.arange(1,10,2))
print(np.arange(20,dtype=complex))
print(np.arange(1,10,2,dtype=float))    #(start,end,difference)

[1 2 3 4 5 6 7 8 9]
[0. 1. 2.]
[1 3 5 7 9]
[ 0.+0.j  1.+0.j  2.+0.j  3.+0.j  4.+0.j  5.+0.j  6.+0.j  7.+0.j  8.+0.j
  9.+0.j 10.+0.j 11.+0.j 12.+0.j 13.+0.j 14.+0.j 15.+0.j 16.+0.j 17.+0.j
 18.+0.j 19.+0.j]
[1. 3. 5. 7. 9.]


In [22]:
a= np.arange(-10,10,1.25) #last value excluded
print(a)

[-10.    -8.75  -7.5   -6.25  -5.    -3.75  -2.5   -1.25   0.     1.25
   2.5    3.75   5.     6.25   7.5    8.75]


In [23]:
b= np.linspace(0,1,10) #last value included/divide values equally
print(b)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [24]:
np.random.random((3,3)) #random values b/w zero to one

array([[0.51785508, 0.0597768 , 0.38825699],
       [0.9687105 , 0.70654934, 0.70642855],
       [0.65297725, 0.33596091, 0.86780306]])

## randint()- this function is used to generate a random number between a given range.
- syntax is 
- rand(min,max,total_values)
- eg. arr=np.random.randint(1,10,3)
- output may be any 3 no. from 1 to 9


In [25]:
arr_4=np.random.randint(1,10,4)
arr_4

array([3, 5, 3, 6])

In [26]:
np.random.randint(1,1000,(3,3)) # random values b/w start and end/last value not included

array([[372, 725, 273],
       [342, 857,  47],
       [523, 161, 393]])

## rand()
- this function is used to generate a random values between 0 to 1.
- syntax- rand(number_of_values)


In [27]:
arr_5=np.random.rand(5)
arr_5

array([0.72394085, 0.54439318, 0.14099504, 0.86095964, 0.95210931])

In [28]:
arr_5=np.random.rand(2,3)
arr_5

array([[0.25083129, 0.23334705, 0.37381516],
       [0.95762513, 0.69865136, 0.52199357]])

## randn()- this function is used to generate a random values close to 0.This may return positive or negative numbers as well.
- syntax
- rand.(number_of_values)
- output may be any 5 numbers from centered to 0

In [29]:
arr_6=np.random.randn(5)
arr_6

array([-1.17220139,  0.69681366,  0.07810073, -2.40271875,  1.52889697])

In [30]:
arr_6=np.random.randn(3,3)
arr_6

array([[-1.40866704,  1.09269288,  0.61862967],
       [-0.98565257,  0.51265202,  0.05393388],
       [ 0.76983887, -1.36659456, -1.16735328]])

## eye()
- This function creates an array with all the diagonal elements as 1 and rest as 0 (in a square matrix). In case of a non-square matrix the values are still 1 for diagonal (upto which it can draw diagonal) and rest are zero

In [31]:
arr_1=np.eye(3)
arr_1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
arr_1=np.eye(3,5)
arr_1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [33]:
np.eye(5,dtype=int) #identity matrix

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

## Ones()

In [34]:
arr4=np.ones(4)
arr4

array([1., 1., 1., 1.])

In [35]:
import numpy as np
arr5=np.ones((2,4))
arr5

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [36]:
np.ones((5,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Zeros()

In [37]:
import numpy as np
arr3=np.zeros(5)
arr3

array([0., 0., 0., 0., 0.])

In [38]:
import numpy as np
arr3=np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [39]:
np.zeros((5,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

## diag()
- This function creates a two dimensional array with all the diagonal elements as the given value and rest as 0 (in a square matrix)

In [40]:
arr_2=np.diag([1,2,3,5,6])
arr_2

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 5, 0],
       [0, 0, 0, 0, 6]])

## To get the diagonal elements in a two dimensional array we use diag as a function

In [41]:
arr_3=np.diag([1,2,3,4])
print(arr_3)
np.diag(arr_3)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


array([1, 2, 3, 4])

# operations
- arithmetic
- statistical
- trignometric
- logical
- slicing
- filtering
- sorting

In [42]:
x= np.random.randint(1,25,(2,3))
y= np.random.randint(1,25,(3,2))
print(x)
print(y)

[[18  8 23]
 [ 1  9  2]]
[[16  2]
 [ 1 22]
 [ 5  2]]


In [43]:
y.T

array([[16,  1,  5],
       [ 2, 22,  2]])

In [44]:
print('x+y transposed')
print(x + y.T)
print('x transposed + y')
print(x.T+y)

x+y transposed
[[34  9 28]
 [ 3 31  4]]
x transposed + y
[[34  3]
 [ 9 31]
 [28  4]]


In [45]:
print('x+y transposed')
print(x - y.T)
print('x transposed + y')
print(x.T-y)

x+y transposed
[[  2   7  18]
 [ -1 -13   0]]
x transposed + y
[[  2  -1]
 [  7 -13]
 [ 18   0]]


In [46]:
print('matix multiplication elemetwise')
print(x * y.T)
print('matix multiplicaton')
print(x @ y)


matix multiplication elemetwise
[[288   8 115]
 [  2 198   4]]
matix multiplicaton
[[411 258]
 [ 35 204]]


In [47]:
np.hstack((x,x,x,x,x))

array([[18,  8, 23, 18,  8, 23, 18,  8, 23, 18,  8, 23, 18,  8, 23],
       [ 1,  9,  2,  1,  9,  2,  1,  9,  2,  1,  9,  2,  1,  9,  2]])

In [48]:
np.hstack((x,x,y.T))

array([[18,  8, 23, 18,  8, 23, 16,  1,  5],
       [ 1,  9,  2,  1,  9,  2,  2, 22,  2]])

In [49]:
print(x)
print('sum of all elements:',x.sum())
print('sum of all elements row wise:',x.sum(axis=1))
print('sum of all elements col  wise:',x.sum(axis=0))
print('average of all elements :',x.mean(axis=0))
print('median of all elements :',np.median(x))
print('min of all elements :',x.min())
print('max of all elements :',x.max())
print('std of all elements :',x.std())
print('variance of all elements :',x.var())
print('any item is non-zero',x.any())
print('all item are non-zero',x.all())


[[18  8 23]
 [ 1  9  2]]
sum of all elements: 61
sum of all elements row wise: [49 12]
sum of all elements col  wise: [19 17 25]
average of all elements : [ 9.5  8.5 12.5]
median of all elements : 8.5
min of all elements : 1
max of all elements : 23
std of all elements : 7.987837977547838
variance of all elements : 63.80555555555554
any item is non-zero True
all item are non-zero True


In [50]:
print(np.pi)
print(np.nan)
print(np.inf)
print(np.e)

3.141592653589793
nan
inf
2.718281828459045


In [51]:
print(np.sin(x))
print(np.cos(x))
print(np.tan(x))

[[-0.75098725  0.98935825 -0.8462204 ]
 [ 0.84147098  0.41211849  0.90929743]]
[[ 0.66031671 -0.14550003 -0.53283302]
 [ 0.54030231 -0.91113026 -0.41614684]]
[[-1.13731371 -6.79971146  1.58815308]
 [ 1.55740772 -0.45231566 -2.18503986]]


## Filtering

In [52]:
x

array([[18,  8, 23],
       [ 1,  9,  2]])

In [53]:
x[x>5]

array([18,  8, 23,  9])

In [54]:
x=np.random.randint(-3,3,(5,5))
x

array([[ 1, -2, -3, -3, -2],
       [-2, -1,  0,  1, -1],
       [-3, -2,  0, -3,  2],
       [-2,  2, -3, -2, -1],
       [-1, -3,  2,  2,  0]])

In [55]:
x[(x>-2) & (x<2)]  #AND-&   #OR-|


array([ 1, -1,  0,  1, -1,  0, -1, -1,  0])

In [56]:
x=np.random.randint(-3,3,(5,5))
x


array([[-1,  0, -1, -3,  1],
       [ 0,  1,  1,  1,  2],
       [ 2,  1, -1,  1,  1],
       [-1,  1, -3,  0,  1],
       [-3, -1, -2, -3, -1]])

### Indexing and Slicing
- syntax for slicing in 1d: [start:stop:step]
- syntax for slicing in 2d:[rstart : rstop : rstep, cstart : cstop : cstop]
- axes 1 - row
- axes 2- col

## indexing in 1d array

In [57]:
import numpy as np
s=np.array([1,2,3,4])
print(s)
print(s[3])
print(s[-2])
print(s[0])

[1 2 3 4]
4
3
1


## indexing in 2d array

In [85]:
x=np.random.randint(-3,3,(5,5))
print(x)
print(x[0,0])

[[ 2 -2  0 -3  2]
 [ 0 -1  2  1  2]
 [-1  0  1 -2  2]
 [ 0  0 -2  2  1]
 [-2  0 -1  0 -1]]
2


In [86]:
x[3,3]

2

In [87]:
x[0]  #first row

array([ 2, -2,  0, -3,  2])

In [88]:
x[-1]  #last row

array([-2,  0, -1,  0, -1])

## Slicing

- syntax for slicing in 1d: [start : stop : step]   (inclusive,exclusive,difference)
- syntax for slicing in 2d:[rstart : rstop : rstep, cstart : cstop : cstop]

## slicing in 1d array

In [90]:
a1=np.array([1,2,3,4,5])
print(a1[1:4])
print(a1[:])
print(a1[1::2])
print(a1[:3])



[2 3 4]
[1 2 3 4 5]
[2 4]
[1 2 3]


## slicing in 2d array

In [92]:
x=np.random.randint(-3,3,(5,5))
print(x)
print(x[0,:3]) #first row first three elements

[[ 1  0 -2 -1 -3]
 [ 1  0 -1  2  1]
 [-1 -2  2 -1 -2]
 [ 0  2 -1 -1 -2]
 [-2 -1  2  2 -3]]
[ 1  0 -2]


In [93]:
print(x[2,-4:])

[-2  2 -1 -2]


In [94]:
print(x[:,0]) # first col.
print(x[:,-1]) # first col.
print(x[:,:2]) # first two col.
print(x[:,[1,3]]) # first index and third index column
print(x[:,[2,4,1,3]]) #2,4,1,3 index column

[ 1  1 -1  0 -2]
[-3  1 -2 -2 -3]
[[ 1  0]
 [ 1  0]
 [-1 -2]
 [ 0  2]
 [-2 -1]]
[[ 0 -1]
 [ 0  2]
 [-2 -1]
 [ 2 -1]
 [-1  2]]
[[-2 -3  0 -1]
 [-1  1  0  2]
 [ 2 -2 -2 -1]
 [-1 -2  2 -1]
 [ 2 -3 -1  2]]


In [82]:
x

array([[-3, -2,  2, -2,  1],
       [-3,  1,  0,  1, -1],
       [-2,  0, -3, -3,  0],
       [-1, -2,  1, -3, -3],
       [ 0, -2,  1, -1,  1]])

In [66]:
x=np.array([[2,2,1],[6,50,6],[7,7,9]])
x

array([[ 2,  2,  1],
       [ 6, 50,  6],
       [ 7,  7,  9]])

In [67]:
x.sort(axis=1)
x

array([[ 1,  2,  2],
       [ 6,  6, 50],
       [ 7,  7,  9]])

In [68]:
x.sort(axis=0)
x

array([[ 1,  2,  2],
       [ 6,  6,  9],
       [ 7,  7, 50]])

In [69]:
x

array([[ 1,  2,  2],
       [ 6,  6,  9],
       [ 7,  7, 50]])

In [70]:
x.max()

50

In [71]:
x.argmax()  #return index of min element

8

In [72]:
x.argmin()   # returns index of min elemen

0