In [9]:
import numpy as np

## Write a NumPy program to create an array of 10 zeros.

In [3]:
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## Write a NumPy program to create an array of 10 ones.

In [4]:
arr1 = np.ones(10)
print(arr1)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


## Write a NumPy program to create a 3x3 matrix with values ranging from 0 to 8.

In [5]:
arr2 = np.arange(9).reshape(3,3)
print(arr2)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


## Write a NumPy program to reverse an array (first element becomes the last).

In [6]:
a= np.array([[1,2,3,4],[5,6,7,8]])
print(a)
b= np.flip(a)
print()
print(b)

[[1 2 3 4]
 [5 6 7 8]]

[[8 7 6 5]
 [4 3 2 1]]


## Write a NumPy program to extract all odd numbers from an array.

## Write a NumPy program to compute the sum of all elements, mean, and standard deviation of a given array.

In [16]:
num =np.random.randint(1,100,(3,3))
print(num)
print('sum:',np.sum(num))
print('mean:',np.mean(num))
print('standard deviation:',np.std(num))


[[ 9 60  9]
 [22 84 75]
 [86 68 83]]
sum: 496
mean: 55.111111111111114
standard deviation: 30.733421707915035


## Write a NumPy program to create a 5x5 matrix with random values and find the minimum and maximum values.

In [13]:
ranval = np.random.randint(1,50,(5,5))
print(ranval)
print('max value:',np.max(ranval))
print('min value:',np.min(ranval))

[[39 42 29 26 11]
 [39 35 25 16 30]
 [48 44 22 23 42]
 [45 19 26 49 16]
 [30 23 27 31 32]]
max value: 49
min value: 11


## Write a NumPy program to create a 2D array with 1 on the border and 0 inside.

## Write a NumPy program to multiply two given matrices.

In [ ]:
a= np.array([[1,2,3,4],[5,6,7,8]])
c = np.array([[6,8,1,2],[4,6,7,8]])
m = np.multiply(a,c)
print(m)

[[ 6 16  3  8]
 [20 36 49 64]]


In [ ]:
x_1= np.random.randint(1,100,(2,3))
x_2= np.random.randint(1,100,(2,3))

x_3 = np.multiply(x_1,x_2)
print(x_3)

[[ 783 2755 1794]
 [1914  455   52]]


## Write a NumPy program to find the unique elements of an array.

In [ ]:
array = [1,2,52,1,6,1,75,7,4,6,4,7,4,7,9,3,6]
np.unique(array)

array([ 1,  2,  3,  4,  6,  7,  9, 52, 75])

## Write a NumPy program to extract the elements in the odd-numbered columns of a 2D array.

In [20]:
arr_1= np.random.randint(1,50,(5,5))
print(arr_1)
print()
print(arr_1[:,[1,3]])

[[ 8 41 46 41 44]
 [10 26  7 28 17]
 [26  4 23 32 24]
 [45  2  8 10  1]
 [ 6 46  9  3 21]]

[[41 41]
 [26 28]
 [ 4 32]
 [ 2 10]
 [46  3]]


## Write a NumPy program to extract the elements in the even-numbered rows of a 2D array.

In [21]:
print(arr_1[[2,4],:])

[[26  4 23 32 24]
 [ 6 46  9  3 21]]


## Write a NumPy program to extract a subarray from a given array. The subarray should include the first 3 rows and the columns from index 1 to 4 (inclusive).

## Write a NumPy program to reverse the order of elements in each column of a 2D array.

## Write a NumPy program to create a diagonal matrix from a given 1D array. The elements below the diagonal should be zero, and the elements above the diagonal should be squared.