## Creating one dimensional array

In [4]:
import numpy as np
a=[1,2,3,4,5]
myarray=np.array(a)
print(myarray)
print(type(myarray))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [6]:
a=[]
n=int(input('Enter size of array'))
for i in range(n):
    val=int(input('enter number'))
    a.append(val)
arr1=np.array(a)    
arr1



array([  45,   45,  358, 5863])

## Creating two dimensional array

In [7]:
import numpy as np                         #a=[[1,2,3],[4,5,6],[7,8,9]]
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])      #arr2=np.array(a)
arr2                                          #arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
# Printing dimension and shape of array
print('Total dimensions-',arr2.ndim)
print('Shape of array-',arr2.shape)

Total dimensions- 2
Shape of array- (3, 3)


In [9]:
import numpy as  np

In [10]:
# creating array with arange function of numpy
a= np.arange(15) #single dimensional
print(a)
a= np.arange(15).reshape(3,5) #multidimentional array
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


## Numpy array properties

In [11]:
# size of array
a.size

15

In [12]:
# dimensions of array
a.ndim

2

In [13]:
x=np.array([1,3,4,5,6])
print(x)

[1 3 4 5 6]


In [14]:
y= np.array([[1,2,3],[2,3,4]])
print(y)

[[1 2 3]
 [2 3 4]]


In [15]:
print('shape',x.shape)
print('num of dimension:',x.ndim)
print('type of data:',x.dtype)
print('Y')
print('shape:',y.shape)
print('num of dimensions:',y.ndim)
print('type of data:',y.dtype)

shape (5,)
num of dimension: 1
type of data: int32
Y
shape: (2, 3)
num of dimensions: 2
type of data: int32


## Functions of array
- arange
- linspace
- random.*
- eye
- ones
- zeros
- diag
- rand


## arange()

In [16]:
print(np.arange(1,10))
print(np.arange(3.0))
print(np.arange(1,10,2))
print(np.arange(20,dtype=complex))
print(np.arange(1,10,2,dtype=float))    #(start,end,difference)

[1 2 3 4 5 6 7 8 9]
[0. 1. 2.]
[1 3 5 7 9]
[ 0.+0.j  1.+0.j  2.+0.j  3.+0.j  4.+0.j  5.+0.j  6.+0.j  7.+0.j  8.+0.j
  9.+0.j 10.+0.j 11.+0.j 12.+0.j 13.+0.j 14.+0.j 15.+0.j 16.+0.j 17.+0.j
 18.+0.j 19.+0.j]
[1. 3. 5. 7. 9.]


In [17]:
a= np.arange(-10,10,1.25) #last value excluded
print(a)

[-10.    -8.75  -7.5   -6.25  -5.    -3.75  -2.5   -1.25   0.     1.25
   2.5    3.75   5.     6.25   7.5    8.75]


In [18]:
b= np.linspace(0,1,10) #last value included/divide values equally
print(b)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [19]:
np.random.random((3,3)) #random values b/w zero to one

array([[0.88804311, 0.59022167, 0.58554   ],
       [0.88731173, 0.39181129, 0.55565373],
       [0.55850075, 0.47185002, 0.75130443]])

## randint()- this function is used to generate a random number between a given range.
- syntax is 
- rand(min,max,total_values)
- eg. arr=np.random.randint(1,10,3)
- output may be any 3 no. from 1 to 9


In [20]:
arr_4=np.random.randint(1,10,4)
arr_4

array([4, 7, 6, 7])

In [21]:
np.random.randint(1,1000,(3,3)) # random values b/w start and end/last value not included

array([[  6, 627, 234],
       [157, 222, 763],
       [ 44, 418, 253]])

## rand()
- this function is used to generate a random values between 0 to 1.
- syntax- rand(number_of_values)


In [22]:
arr_5=np.random.rand(5)
arr_5

array([0.03370864, 0.28059536, 0.23349829, 0.84089039, 0.60397727])

In [23]:
arr_5=np.random.rand(2,3)
arr_5

array([[0.09636395, 0.2703695 , 0.84957555],
       [0.7099882 , 0.97825324, 0.52533696]])

## randn()- this function is used to generate a random values close to 0.This may return positive or negative numbers as well.
- syntax
- rand.(number_of_values)
- output may be any 5 numbers from centered to 0

In [24]:
arr_6=np.random.randn(5)
arr_6

array([ 0.78451707, -0.66300436,  0.82870369,  0.52027755,  1.41671701])

In [25]:
arr_6=np.random.randn(3,3)
arr_6

array([[-0.39245448,  0.17890921, -2.39509392],
       [-1.20402443, -0.16671304, -1.15919951],
       [-0.76525155, -1.39478803, -0.76946642]])

## eye()
- This function creates an array with all the diagonal elements as 1 and rest as 0 (in a square matrix). In case of a non-square matrix the values are still 1 for diagonal (upto which it can draw diagonal) and rest are zero

In [26]:
arr_1=np.eye(3)
arr_1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
arr_1=np.eye(3,5)
arr_1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [28]:
np.eye(5,dtype=int) #identity matrix

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

## Ones()

In [29]:
arr4=np.ones(4)
arr4

array([1., 1., 1., 1.])

In [30]:
import numpy as np
arr5=np.ones((2,4))
arr5

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [31]:
np.ones((5,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Zeros()

In [32]:
import numpy as np
arr3=np.zeros(5)
arr3

array([0., 0., 0., 0., 0.])

In [33]:
import numpy as np
arr3=np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [34]:
np.zeros((5,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

## diag()
- This function creates a two dimensional array with all the diagonal elements as the given value and rest as 0 (in a square matrix)

In [35]:
arr_2=np.diag([1,2,3,5,6])
arr_2

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 5, 0],
       [0, 0, 0, 0, 6]])

## To get the diagonal elements in a two dimensional array we use diag as a function

In [36]:
arr_3=np.diag([1,2,3,4])
print(arr_3)
np.diag(arr_3)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


array([1, 2, 3, 4])

# operations
- arithmetic
- statistical
- trignometric
- logical
- slicing
- filtering
- sorting

In [37]:
x= np.random.randint(1,25,(2,3))
y= np.random.randint(1,25,(3,2))
print(x)
print(y)

[[15 17 15]
 [13  8  4]]
[[12 13]
 [24  5]
 [ 6 15]]


In [38]:
y.T

array([[12, 24,  6],
       [13,  5, 15]])

In [39]:
print('x+y transposed')
print(x + y.T)
print('x transposed + y')
print(x.T+y)

x+y transposed
[[27 41 21]
 [26 13 19]]
x transposed + y
[[27 26]
 [41 13]
 [21 19]]


In [40]:
print('x+y transposed')
print(x - y.T)
print('x transposed + y')
print(x.T-y)

x+y transposed
[[  3  -7   9]
 [  0   3 -11]]
x transposed + y
[[  3   0]
 [ -7   3]
 [  9 -11]]


In [41]:
print('matix multiplication elemetwise')
print(x * y.T)
print('matix multiplicaton')
print(x @ y)


matix multiplication elemetwise
[[180 408  90]
 [169  40  60]]
matix multiplicaton
[[678 505]
 [372 269]]


In [42]:
np.hstack((x,x,x,x,x))

array([[15, 17, 15, 15, 17, 15, 15, 17, 15, 15, 17, 15, 15, 17, 15],
       [13,  8,  4, 13,  8,  4, 13,  8,  4, 13,  8,  4, 13,  8,  4]])

In [43]:
np.hstack((x,x,y.T))

array([[15, 17, 15, 15, 17, 15, 12, 24,  6],
       [13,  8,  4, 13,  8,  4, 13,  5, 15]])

In [44]:
print(x)
print('sum of all elements:',x.sum())
print('sum of all elements row wise:',x.sum(axis=1))
print('sum of all elements col  wise:',x.sum(axis=0))
print('average of all elements :',x.mean(axis=0))
print('median of all elements :',np.median(x))
print('min of all elements :',x.min())
print('max of all elements :',x.max())
print('std of all elements :',x.std())
print('variance of all elements :',x.var())
print('any item is non-zero',x.any())
print('all item are non-zero',x.all())


[[15 17 15]
 [13  8  4]]
sum of all elements: 72
sum of all elements row wise: [47 25]
sum of all elements col  wise: [28 25 19]
average of all elements : [14.  12.5  9.5]
median of all elements : 14.0
min of all elements : 4
max of all elements : 17
std of all elements : 4.546060565661952
variance of all elements : 20.666666666666668
any item is non-zero True
all item are non-zero True


In [45]:
print(np.pi)
print(np.nan)
print(np.inf)
print(np.e)

3.141592653589793
nan
inf
2.718281828459045


In [46]:
print(np.sin(x))
print(np.cos(x))
print(np.tan(x))

[[ 0.65028784 -0.96139749  0.65028784]
 [ 0.42016704  0.98935825 -0.7568025 ]]
[[-0.75968791 -0.27516334 -0.75968791]
 [ 0.90744678 -0.14550003 -0.65364362]]
[[-0.8559934   3.49391565 -0.8559934 ]
 [ 0.46302113 -6.79971146  1.15782128]]


In [47]:
x

array([[15, 17, 15],
       [13,  8,  4]])

In [48]:
x[x>5]

array([15, 17, 15, 13,  8])

In [51]:
x=np.random.randint(-3,3,(5,5))
x

array([[-3,  0, -3, -1, -1],
       [-1, -3, -3, -2, -1],
       [-1,  1,  2, -2, -2],
       [-2,  2, -3,  1, -2],
       [ 1,  0, -1, -2,  0]])

In [50]:
x[(x>-2) & (x<2)]  #AND-&   #OR-|


array([-1,  1,  0,  1,  0,  1, -1,  0,  0,  0, -1, -1,  1])

In [52]:
x=np.random.randint(-3,3,(5,5))
x

array([[-3, -2,  2, -1,  2],
       [-3,  2, -3, -3,  2],
       [ 0, -1, -3,  0, -3],
       [-1,  1,  2,  1,  0],
       [ 2, -1, -2,  2, -2]])

### Indexing and Slicing
- syntax for slicing in 1d: [start:stop:step]
- syntax for slicing in 2d:[rstart:rstop:rstep, cstart:cstop:cstop]
- axes 1 - row
- axes 2- col

In [53]:
x[0,0]

-3

In [54]:
x[3,3]

1

In [55]:
x[0]  #first row

array([-3, -2,  2, -1,  2])

In [56]:
x[-1]  #last row

array([ 2, -1, -2,  2, -2])

In [70]:
x=np.random.randint(-3,3,(5,5))
print(x)
print(x[0,:3]) #first row first three elements

[[-2  1 -2  0 -3]
 [-1 -1  2 -1  2]
 [-3 -1 -3  1  0]
 [ 0 -1 -1 -2  1]
 [-2 -1  1 -3 -2]]
[-2  1 -2]


In [59]:
print(x[2,-4:])

[-1 -3  0 -3]


In [66]:
print(x[:,0]) # first col.
print(x[:,-1]) # first col.
print(x[:,:2]) # first two col.
print(x[:,[1,3]]) # first index and third index column
print(x[:,[2,4,1,3]]) #2,4,1,3 index column

[-3 -3  0 -1  2]
[ 2  2 -3  0 -2]
[[-3 -2]
 [-3  2]
 [ 0 -1]
 [-1  1]
 [ 2 -1]]
[[-2 -1]
 [ 2 -3]
 [-1  0]
 [ 1  1]
 [-1  2]]
[[ 2  2 -2 -1]
 [-3  2  2 -3]
 [-3 -3 -1  0]
 [ 2  0  1  1]
 [-2 -2 -1  2]]


In [73]:
x

array([[-3, -2, -2,  0,  1],
       [-1, -1, -1,  2,  2],
       [-3, -3, -1,  0,  1],
       [-2, -1, -1,  0,  1],
       [-3, -2, -2, -1,  1]])

In [77]:
x=np.array([[2,2,1],[6,50,6],[7,7,9]])
x

array([[ 2,  2,  1],
       [ 6, 50,  6],
       [ 7,  7,  9]])

In [79]:
x.sort(axis=1)
x

array([[ 1,  2,  2],
       [ 6,  6, 50],
       [ 7,  7,  9]])

In [74]:
x.sort(axis=0)
x

array([[-3, -3, -2, -1,  1],
       [-3, -2, -2,  0,  1],
       [-3, -2, -1,  0,  1],
       [-2, -1, -1,  0,  1],
       [-1, -1, -1,  2,  2]])

In [85]:
x

array([[ 1,  2,  2],
       [ 6,  6, 50],
       [ 7,  7,  9]])

In [80]:
x.max()

50

In [83]:
x.argmax()  #return index of min element

5

In [84]:
x.argmin()   # returns index of min elemen

0