In [1]:
import numpy as np

## Write a NumPy program to create an array of 10 zeros.

In [2]:
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## Write a NumPy program to create an array of 10 ones.

In [3]:
arr1 = np.ones(10)
print(arr1)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


## Write a NumPy program to create a 3x3 matrix with values ranging from 0 to 8.

In [4]:
arr2 = np.arange(9).reshape(3,3)
print(arr2)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


## Write a NumPy program to reverse an array (first element becomes the last).

In [5]:
a= np.array([[1,2,3,4],[5,6,7,8]])
print(a)
b= np.flip(a)
print()
print(b)

[[1 2 3 4]
 [5 6 7 8]]

[[8 7 6 5]
 [4 3 2 1]]


## Write a NumPy program to extract all odd numbers from an array.

In [16]:
print(a[a%2!=0])


[1 3 5 7]


## Write a NumPy program to compute the sum of all elements, mean, and standard deviation of a given array.

In [6]:
num =np.random.randint(1,100,(3,3))
print(num)
print('sum:',np.sum(num))
print('mean:',np.mean(num))
print('standard deviation:',np.std(num))


[[93 76 25]
 [79 51  3]
 [49 40 66]]
sum: 482
mean: 53.55555555555556
standard deviation: 26.75863769622857


## Write a NumPy program to create a 5x5 matrix with random values and find the minimum and maximum values.

In [7]:
ranval = np.random.randint(1,50,(5,5))
print(ranval)
print('max value:',np.max(ranval))
print('min value:',np.min(ranval))

[[31 30 39  9 24]
 [21 34 25 47 29]
 [39  6 48 42  2]
 [32 43 35 11 34]
 [26 10  2 16 13]]
max value: 48
min value: 2


## Write a NumPy program to create a 2D array with 1 on the border and 0 inside.

## Write a NumPy program to multiply two given matrices.

In [8]:
a= np.array([[1,2,3,4],[5,6,7,8]])
c = np.array([[6,8,1,2],[4,6,7,8]])
m = np.multiply(a,c)
print(m)

[[ 6 16  3  8]
 [20 36 49 64]]


In [9]:
x_1= np.random.randint(1,100,(2,3))
x_2= np.random.randint(1,100,(2,3))

x_3 = np.multiply(x_1,x_2)
print(x_3)

[[1288  450  558]
 [3444 1577 4941]]


## Write a NumPy program to find the unique elements of an array.

In [10]:
array = [1,2,52,1,6,1,75,7,4,6,4,7,4,7,9,3,6]
np.unique(array)

array([ 1,  2,  3,  4,  6,  7,  9, 52, 75])

## Write a NumPy program to extract the elements in the odd-numbered columns of a 2D array.

In [11]:
arr_1= np.random.randint(1,50,(5,5))
print(arr_1)
print()
print(arr_1[:,[1,3]])

[[ 6 47 40 38 43]
 [39 32 31 12  7]
 [13  2 20  5 24]
 [41  5 36  4 21]
 [27 44 34 37 11]]

[[47 38]
 [32 12]
 [ 2  5]
 [ 5  4]
 [44 37]]


## Write a NumPy program to extract the elements in the even-numbered rows of a 2D array.

In [12]:
print(arr_1[[2,4],:])

[[13  2 20  5 24]
 [27 44 34 37 11]]


## Write a NumPy program to extract a subarray from a given array. The subarray should include the first 3 rows and the columns from index 1 to 4 (inclusive).

## Write a NumPy program to reverse the order of elements in each column of a 2D array.

## Write a NumPy program to create a diagonal matrix from a given 1D array. The elements below the diagonal should be zero, and the elements above the diagonal should be squared.