## Creating one dimensional array

In [2]:
import numpy as np
a=[1,2,3,4,5]
myarray=np.array(a)
print(myarray)
print(type(myarray))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [4]:
a=[]
n=int(input('Enter size of array'))
for i in range(n):
    val=int(input('enter number'))
    a.append(val)
arr1=np.array(a)    
arr1



array([1, 1, 2, 3, 4])

## Creating two dimensional array

In [5]:
import numpy as np                         #a=[[1,2,3],[4,5,6],[7,8,9]]
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])      #arr2=np.array(a)
arr2                                          #arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
# Printing dimension and shape of array
print('Total dimensions-',arr2.ndim)
print('Shape of array-',arr2.shape)

Total dimensions- 2
Shape of array- (3, 3)


In [7]:
import numpy as  np

In [8]:
# creating array with arange function of numpy
a= np.arange(15) #single dimensional
print(a)
a= np.arange(15).reshape(3,5) #multidimentional array
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


## Numpy array properties

In [9]:
# size of array
a.size

15

In [10]:
# dimensions of array
a.ndim

2

In [11]:
x=np.array([1,3,4,5,6])
print(x)

[1 3 4 5 6]


In [12]:
y= np.array([[1,2,3],[2,3,4]])
print(y)

[[1 2 3]
 [2 3 4]]


In [13]:
print('shape',x.shape)
print('num of dimension:',x.ndim)
print('type of data:',x.dtype)
print('Y')
print('shape:',y.shape)
print('num of dimensions:',y.ndim)
print('type of data:',y.dtype)

shape (5,)
num of dimension: 1
type of data: int32
Y
shape: (2, 3)
num of dimensions: 2
type of data: int32


## Functions of array
- arange
- linspace
- random.*
- eye
- ones
- zeros
- diag
- rand


## arange()

In [14]:
print(np.arange(1,10))
print(np.arange(3.0))
print(np.arange(1,10,2))
print(np.arange(20,dtype=complex))
print(np.arange(1,10,2,dtype=float))    #(start,end,difference)

[1 2 3 4 5 6 7 8 9]
[0. 1. 2.]
[1 3 5 7 9]
[ 0.+0.j  1.+0.j  2.+0.j  3.+0.j  4.+0.j  5.+0.j  6.+0.j  7.+0.j  8.+0.j
  9.+0.j 10.+0.j 11.+0.j 12.+0.j 13.+0.j 14.+0.j 15.+0.j 16.+0.j 17.+0.j
 18.+0.j 19.+0.j]
[1. 3. 5. 7. 9.]


In [15]:
a= np.arange(-10,10,1.25) #last value excluded
print(a)

[-10.    -8.75  -7.5   -6.25  -5.    -3.75  -2.5   -1.25   0.     1.25
   2.5    3.75   5.     6.25   7.5    8.75]


In [16]:
b= np.linspace(0,1,10) #last value included/divide values equally
print(b)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [17]:
np.random.random((3,3)) #random values b/w zero to one

array([[0.14818137, 0.9748742 , 0.39191485],
       [0.19908263, 0.49153632, 0.6742242 ],
       [0.87666992, 0.397634  , 0.42508521]])

## randint()- this function is used to generate a random number between a given range.
- syntax is 
- rand(min,max,total_values)
- eg. arr=np.random.randint(1,10,3)
- output may be any 3 no. from 1 to 9


In [18]:
arr_4=np.random.randint(1,10,4)
arr_4

array([1, 4, 2, 3])

In [19]:
np.random.randint(1,1000,(3,3)) # random values b/w start and end/last value not included

array([[951, 486,  80],
       [629,  55, 787],
       [  1, 170,   1]])

## rand()
- this function is used to generate a random values between 0 to 1.
- syntax- rand(number_of_values)


In [20]:
arr_5=np.random.rand(5)
arr_5

array([0.54256373, 0.78766962, 0.49245593, 0.57205613, 0.13055965])

In [21]:
arr_5=np.random.rand(2,3)
arr_5

array([[0.64038589, 0.79379329, 0.63266372],
       [0.43134496, 0.66346329, 0.37995559]])

## randn()- this function is used to generate a random values close to 0.This may return positive or negative numbers as well.
- syntax
- rand.(number_of_values)
- output may be any 5 numbers from centered to 0

In [22]:
arr_6=np.random.randn(5)
arr_6

array([-1.0355872 , -0.01929446, -0.7580268 , -0.99427522,  1.38328424])

In [23]:
arr_6=np.random.randn(3,3)
arr_6

array([[ 2.58109037,  0.06751768,  0.88425547],
       [-0.71206746,  0.12243041, -2.56188896],
       [ 0.19055889,  0.95042655, -1.15293562]])

## eye()
- This function creates an array with all the diagonal elements as 1 and rest as 0 (in a square matrix). In case of a non-square matrix the values are still 1 for diagonal (upto which it can draw diagonal) and rest are zero

In [24]:
arr_1=np.eye(3)
arr_1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
arr_1=np.eye(3,5)
arr_1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [26]:
np.eye(5,dtype=int) #identity matrix

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

## Ones()

In [27]:
arr4=np.ones(4)
arr4

array([1., 1., 1., 1.])

In [28]:
import numpy as np
arr5=np.ones((2,4))
arr5

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [29]:
np.ones((5,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Zeros()

In [30]:
import numpy as np
arr3=np.zeros(5)
arr3

array([0., 0., 0., 0., 0.])

In [31]:
import numpy as np
arr3=np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [32]:
np.zeros((5,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

## diag()
- This function creates a two dimensional array with all the diagonal elements as the given value and rest as 0 (in a square matrix)

In [33]:
arr_2=np.diag([1,2,3,5,6])
arr_2

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 5, 0],
       [0, 0, 0, 0, 6]])

## To get the diagonal elements in a two dimensional array we use diag as a function

In [34]:
arr_3=np.diag([1,2,3,4])
print(arr_3)
np.diag(arr_3)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


array([1, 2, 3, 4])

# operations
- arithmetic
- statistical
- trignometric
- logical
- slicing
- filtering
- sorting

In [35]:
x= np.random.randint(1,25,(2,3))
y= np.random.randint(1,25,(3,2))
print(x)
print(y)

[[24 10  9]
 [21 13 17]]
[[17  3]
 [ 2  7]
 [ 9 22]]


In [36]:
y.T

array([[17,  2,  9],
       [ 3,  7, 22]])

In [37]:
print('x+y transposed')
print(x + y.T)
print('x transposed + y')
print(x.T+y)

x+y transposed
[[41 12 18]
 [24 20 39]]
x transposed + y
[[41 24]
 [12 20]
 [18 39]]


In [38]:
print('x+y transposed')
print(x - y.T)
print('x transposed + y')
print(x.T-y)

x+y transposed
[[ 7  8  0]
 [18  6 -5]]
x transposed + y
[[ 7 18]
 [ 8  6]
 [ 0 -5]]


In [39]:
print('matix multiplication elemetwise')
print(x * y.T)
print('matix multiplicaton')
print(x @ y)


matix multiplication elemetwise
[[408  20  81]
 [ 63  91 374]]
matix multiplicaton
[[509 340]
 [536 528]]


In [40]:
np.hstack((x,x,x,x,x))

array([[24, 10,  9, 24, 10,  9, 24, 10,  9, 24, 10,  9, 24, 10,  9],
       [21, 13, 17, 21, 13, 17, 21, 13, 17, 21, 13, 17, 21, 13, 17]])

In [41]:
np.hstack((x,x,y.T))

array([[24, 10,  9, 24, 10,  9, 17,  2,  9],
       [21, 13, 17, 21, 13, 17,  3,  7, 22]])

In [42]:
print(x)
print('sum of all elements:',x.sum())
print('sum of all elements row wise:',x.sum(axis=1))
print('sum of all elements col  wise:',x.sum(axis=0))
print('average of all elements :',x.mean(axis=0))
print('median of all elements :',np.median(x))
print('min of all elements :',x.min())
print('max of all elements :',x.max())
print('std of all elements :',x.std())
print('variance of all elements :',x.var())
print('any item is non-zero',x.any())
print('all item are non-zero',x.all())


[[24 10  9]
 [21 13 17]]
sum of all elements: 94
sum of all elements row wise: [43 51]
sum of all elements col  wise: [45 23 26]
average of all elements : [22.5 11.5 13. ]
median of all elements : 15.0
min of all elements : 9
max of all elements : 24
std of all elements : 5.527707983925667
variance of all elements : 30.555555555555557
any item is non-zero True
all item are non-zero True


In [43]:
print(np.pi)
print(np.nan)
print(np.inf)
print(np.e)

3.141592653589793
nan
inf
2.718281828459045


In [44]:
print(np.sin(x))
print(np.cos(x))
print(np.tan(x))

[[-0.90557836 -0.54402111  0.41211849]
 [ 0.83665564  0.42016704 -0.96139749]]
[[ 0.42417901 -0.83907153 -0.91113026]
 [-0.54772926  0.90744678 -0.27516334]]
[[-2.1348967   0.64836083 -0.45231566]
 [-1.52749853  0.46302113  3.49391565]]


## Filtering

In [45]:
x

array([[24, 10,  9],
       [21, 13, 17]])

In [46]:
x[x>5]

array([24, 10,  9, 21, 13, 17])

In [47]:
x=np.random.randint(-3,3,(5,5))
x

array([[-3, -2, -2,  1, -1],
       [ 2,  1, -1,  1,  2],
       [ 0, -1,  2, -2, -3],
       [ 2, -3, -2, -3,  2],
       [-3, -1,  0, -2, -1]])

In [48]:
x[(x>-2) & (x<2)]  #AND-&   #OR-|


array([ 1, -1,  1, -1,  1,  0, -1, -1,  0, -1])

In [49]:
x=np.random.randint(-3,3,(5,5))
x


array([[ 2,  1,  2,  0,  0],
       [ 0, -1,  2,  0,  2],
       [ 0, -2, -2,  0,  1],
       [ 1, -2, -2, -3,  0],
       [-2, -1, -2,  2, -1]])

### Indexing and Slicing
- syntax for slicing in 1d: [start:stop:step]
- syntax for slicing in 2d:[rstart : rstop : rstep, cstart : cstop : cstep]
- axes 1 - row
- axes 2- col

## indexing in 1d array

In [50]:
import numpy as np
s=np.array([1,2,3,4])
print(s)
print(s[3])
print(s[-2])
print(s[0])

[1 2 3 4]
4
3
1


## indexing in 2d array

In [51]:
x=np.random.randint(-3,3,(5,5))
print(x)
print(x[0,0])

[[-3 -2  2 -1  2]
 [ 2  1 -3 -2 -2]
 [ 0 -3 -3 -2 -1]
 [ 2 -1 -1  1  2]
 [ 2 -3 -3  0  2]]
-3


In [52]:
x[3,3]

1

In [53]:
x[0]  #first row

array([-3, -2,  2, -1,  2])

In [54]:
x[-1]  #last row

array([ 2, -3, -3,  0,  2])

## Slicing

- syntax for slicing in 1d: [start : stop : step]   (inclusive,exclusive,difference)
- syntax for slicing in 2d:[rstart : rstop : rstep, cstart : cstop : cstep]

## slicing in 1d array

In [55]:
a1=np.array([1,2,3,4,5])
print(a1[1:4])
print(a1[:])
print(a1[1::2])
print(a1[:3])



[2 3 4]
[1 2 3 4 5]
[2 4]
[1 2 3]


## slicing in 2d array

In [69]:
x=np.random.randint(-3,3,(5,5))
print(x)
print(x[0,:3]) #first row first three elements

[[-2  2  1  0 -2]
 [-2  0 -3 -2 -3]
 [ 0 -2 -2  0  2]
 [ 0  0  2  2 -3]
 [-1 -2 -2  0  1]]
[-2  2  1]


In [70]:
print(x[2,-4:])

[-2 -2  0  2]


In [71]:
print(x[:,0]) # first col.                                    
print(x[:,-1]) # last col.
print(x[:,:2]) # first two col.
print(x[:,[1,3]]) # first index and third index column  ##extract the elements in the odd-numbered columns of a 2D array.
print(x[:,[2,4,1,3]]) #2,4,1,3 index column

[-2 -2  0  0 -1]
[-2 -3  2 -3  1]
[[-2  2]
 [-2  0]
 [ 0 -2]
 [ 0  0]
 [-1 -2]]
[[ 2  0]
 [ 0 -2]
 [-2  0]
 [ 0  2]
 [-2  0]]
[[ 1 -2  2  0]
 [-3 -3  0 -2]
 [-2  2 -2  0]
 [ 2 -3  0  2]
 [-2  1 -2  0]]


## extract the elements in the odd-numbered columns of a 2D array.

In [72]:
array = np.random.randint(1,100, (5, 5))
print(array)
print(array[:, 1::2])

[[44 40 51 85 63]
 [31 74  4 23 99]
 [80 96 35 57 38]
 [97 55 91 59 96]
 [22 35 47 51 96]]
[[40 85]
 [74 23]
 [96 57]
 [55 59]
 [35 51]]


In [59]:
x

array([[ 2,  0,  1,  1, -1],
       [ 2, -2,  0,  2,  0],
       [ 2,  1, -1, -1,  2],
       [ 1, -2,  1, -3, -1],
       [-1, -2,  0,  2, -1]])

In [60]:
x=np.array([[2,2,1],[6,50,6],[7,7,9]])
x

array([[ 2,  2,  1],
       [ 6, 50,  6],
       [ 7,  7,  9]])

In [61]:
x.sort(axis=1)
x

array([[ 1,  2,  2],
       [ 6,  6, 50],
       [ 7,  7,  9]])

In [62]:
x.sort(axis=0)
x

array([[ 1,  2,  2],
       [ 6,  6,  9],
       [ 7,  7, 50]])

In [63]:
x

array([[ 1,  2,  2],
       [ 6,  6,  9],
       [ 7,  7, 50]])

In [64]:
x.max()

50

In [65]:
x.argmax()  #return index of min element

8

In [66]:
x.argmin()   # returns index of min elemen

0